version: '3.8'

services:
        php:
                build:
                        dockerfile: ./.docker/php/Dockerfile
                        context: .
                volumes:
                        - ./api/:/var/www/html
        # web:
        #         image: nginx:1.19
        #         volumes:
        #                 - ./frontend:/assets
        #                 - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        #         ports:
        #                 - "80:80"
        node:
                image: node:16
                user: node
                working_dir: /assets
                environment:
                        - HOST=0.0.0.0
                        - PORT=3000
                volumes:
                        - ./frontend:/assets
                command: npm run dev
                ports:
                        - "3000:3000"

        db:
                image: mariadb:10.6
                environment:
                        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
                        MYSQL_ROOT_HOST: "%"
                        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
                        MYSQL_DATABASE: "${DB_DATABASE}"
                        MYSQL_USER: "${DB_USERNAME}"
                        MYSQL_PASSWORD: "${DB_PASSWORD}"
                volumes:
                        - mysqldata:/var/lib/mysql
                ports:
                        - "4306:3306"
        redis:
                image: redis
                volumes:
                        - redisdata:/data
        # supervisor:
        #         build:
        #                 context: .
        #                 dockerfile: .docker/supervisord/Dockerfile
        #         volumes:
        #                 - ./src:/var/www/html
volumes:
        mysqldata:
        redisdata:
