version: '3.8'

services:
        php:
                build:
                        dockerfile: ./.docker/php/Dockerfile
                        context: .
                volumes:
                        - ./api/:/var/www/html
                #hostname: api
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                ports:
                        - 9000:9000
        web:
                image: nginx:1.21-alpine
                volumes:
                        # - ./frontend:/assets
                        - ./.docker/nginx:/etc/nginx/conf.d
                        - ./.docker/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
                        - ./.docker/nginx/snippets:/etc/nginx/snippets:ro
                        - ./.docker/nginx/default.conf:/etc/nginx/nginx.conf:ro
                ports:
                        - "80:80"
        node:
                image: node:lts
                user: node
                working_dir: /assets
                environment:
                        - HOST=0.0.0.0
                        - PORT=3000
                volumes:
                        - ./frontend:/assets
                command: npm run dev
                ports:
                        - 3000:3000

        db:
                image: mariadb:10.6
                volumes:
                        - mysqldata:/var/lib/mysql
                ports:
                        - 4306:3306
                environment:
                        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
                        MYSQL_DATABASE: "${DB_DATABASE}"
                        MYSQL_USER: "${DB_USERNAME}"
                        MYSQL_PASSWORD: "${DB_PASSWORD}"
        redis:
                image: redis
                volumes:
                        - redisdata:/data
        # supervisor:
        #         build:
        #                 context: ./api
        #                 dockerfile: .docker/supervisord/Dockerfile
        #         volumes:
        #                 - ./:/var/www/html

        mailgoh:
                image: mailhog/mailhog:latest
                ports:
                        - 1025:1025
                        - 8025:8025
                
volumes:
        mysqldata:
        redisdata:
