version: '3.8'

services:
        php:
                build:
                        dockerfile: ./.docker/php/Dockerfile
                        context: .
                volumes:
                        - ./api/:/var/www/html
                # hostname: api
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                ports:
                        - "${PHP_PORT}:9000"

        web:
                image: nginx:1.21-alpine
                volumes:
                        # - ./frontend:/assets
                        - ./.docker/nginx:/etc/nginx/conf.d
                        - ./.docker/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
                        - ./.docker/nginx/snippets:/etc/nginx/snippets:ro
                        - ./.docker/nginx/default.conf:/etc/nginx/nginx.conf:ro
                ports:
                        - "${WEB_PORT}:80"

        node:
                image: node:lts
                user: node
                working_dir: /assets
                environment:
                        - HOST=0.0.0.0
                        - PORT=${NODE_PORT}
                volumes:
                        - ./frontend:/assets
                command: npm run dev
                ports:
                        - "${NODE_PORT}:3000"

        db:
                image: mariadb:10.6
                volumes:
                        - ./mysqldata:/var/lib/mysql
                ports:
                        - "${DB_PORT}:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
                        MYSQL_DATABASE: "${DB_DATABASE}"
                        MYSQL_USER: "${DB_USERNAME}"
                        MYSQL_PASSWORD: "${DB_PASSWORD}"
        redis:
                image: redis
                volumes:
                        - ./redisdata:/data
        supervisor:
                build:
                        context: ./
                        dockerfile: .docker/supervisord/Dockerfile
                volumes:
                        - ./api:/var/www/html

        mailgoh:
                image: mailhog/mailhog:latest
                ports:
                        - "${MAILHOG_SMTP_PORT}:1025"
                        - "${MAILHOG_HTTP_PORT}:8025"

        meilisearch:
                image: getmeili/meilisearch:latest
                volumes:
                        - ./meilisearch:/meili_data
                ports: 
                        - "${MEILISEARCH_PORT}:7700"
        
                
# volumes:
#         mysqldata:
#         redisdata:
